config/routes.rb
OauthClient::Application.routes.draw do
  get '/auth', to: 'sessions#show'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy', as: 'signout'
  resources :products
  resources :variants
  resources :barcodes, only: :show
  root to: 'products#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid =      auth["uid"]
      user.name =     auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AuthController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/barcodes_controller.rb
class BarcodesController < ApplicationController
  def show
    require 'barby/barcode/ean_13'
    require 'barby/outputter/ascii_outputter'
    require 'barby/outputter/html_outputter'
    require 'barby/outputter/pdfwriter_outputter'
    require 'barby/outputter/png_outputter'
    require 'barby/outputter/rmagick_outputter'
    require 'barby/outputter/svg_outputter'
    @barcode = Barby::EAN13.new(params[:id])
    respond_to do |format|
      format.html
      format.png do
        send_data @barcode.to_png(xdim: (params[:width] || 3).to_i)
      end
      format.gif do
        send_data @barcode.to_gif(xdim: (params[:width] || 3).to_i)
      end
      format.jpg do
        send_data @barcode.to_jpg(xdim: (params[:width] || 3).to_i)
      end
    end
  end
end

app/controllers/concerns/auth_controller.rb
module AuthController
  extend ActiveSupport::Concern

  included do
    rescue_from OAuth2::Error do |exception|
      if exception.response.status == 401
        clear_session
        redirect_to root_url, alert: "Access token expired, try signing in again."
      else
        raise
      end
    end

    helper_method :access_token
  end

private
  def oauth_client
    @oauth_client ||= OAuth2::Client.new(ENV["OAUTH_ID"], ENV["OAUTH_SECRET"], site: "https://api.tradegecko.com")
  end

  def access_token
    if session[:access_token]
      @access_token ||= begin
        token = OAuth2::AccessToken.new(oauth_client, session[:access_token],
                refresh_token: session[:refresh_token],
                expires_at: session[:expires_at]
        )
        AccessTokenWrapper::Base.new(token) do |new_token, exception|
          set_session_from_access_token(new_token)
        end
      end
    end
  end

  def clear_session
    session.delete(:user_id)
    session.delete(:access_token)
    session.delete(:refresh_token)
    session.delete(:expires_at)
  end

  def set_session_from_access_token(access_token)
    session[:access_token]  = access_token.token
    session[:refresh_token] = access_token.refresh_token
    session[:expires_at]    = access_token.expires_at
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = access_token.get("/products").parsed["products"] if access_token
  end

  def show
    @product = access_token.get("/products/#{params[:id]}").parsed["product"]
  end

  def new
  end

  def create
    access_token.post("/products", params: {product: {name: params[:name]}})
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.where(provider: auth["provider"], uid: auth["uid"].to_s).first || User.create_with_omniauth(auth)
    token = OAuth2::AccessToken.new(oauth_client, auth["credentials"]["token"], auth["credentials"].slice("refresh_token", "expires_at"))
    session[:user_id] = user.id
    set_session_from_access_token(token)
    redirect_to root_url
  end

  def destroy
    clear_session
    redirect_to root_url
  end

private
  def auth
    request.env["omniauth.auth"]
  end
end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
  def index
    @variants = access_token.get("/variants").parsed["variants"]
  end

  def show
    @variant = access_token.get("/variants/#{params[:id]}").parsed["variant"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/barcodes/show.html.erb
<style type="text/css">
  table.barby-barcode { border-spacing: 0; }
  tr.barby-row {}
  td.barby-cell { width: 2px; height: 100px; }
  td.barby-cell.on { background: #000; }
</style>

<h3>HTML</h3>
<%= raw @barcode.to_html %>

<h3>ASCII</h3>
<div style="width:590px;font-size:0.8em;font-weight:800">
  <%= @barcode.to_ascii %>
</div>

<h3>PNG</h3>
<%= image_tag barcode_path @barcode.data, format: :png %>

<h3>SVG</h3>
<%= raw @barcode.to_svg(xdim: 3) %>

<h3>GIF</h3>
<%= image_tag barcode_path @barcode.data, format: :gif %>

<h3>JPG</h3>
<%= image_tag barcode_path @barcode.data, format: :jpg %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TradeGecko Example</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/products/index.html.erb
<h1>Products List</h1>

<% if current_user %>
  <ul id="tasks">
  <% @products.each do |product| %>
    <li><%= link_to product["name"], product_path(product['id']) %></li>
  <% end %>
  </ul>

  <p id="logged_in">
    Logged in as <strong><%= current_user.name %></strong>.
    <%= link_to "Sign Out", signout_path %>
  </p>
<% else %>
  <p><strong>Currently not signed in.</strong></p>
  <p>
    <%= link_to "Sign in through TradeGecko", "/auth/tradegecko" %>
  </p>
<% end %>

app/views/products/new.html.erb
<%= form_tag products_path do %>
  <%= text_field_tag :name %>
  <%= submit_tag "Add" %>
<% end %>

app/views/products/show.html.erb
<ul>
  <% @product.each do |name, value| %>
    <li><%= name.titleize %>: <%= value %></li>
  <% end %>
</ul>
<p><%= link_to "Back", root_path %></p>

app/views/tasks/index.html.erb
<h1>To Do List</h1>

<% if current_user %>
  <%= form_tag tasks_path do %>
    <%= text_field_tag :name %>
    <%= submit_tag "Add" %>
  <% end %>

  <ul id="tasks">
  <% @tasks.each do |task| %>
    <li><%= task["name"] %></li>
  <% end %>
  </ul>

  <p id="logged_in">
    Logged in as <strong><%= current_user.name %></strong>.
    <%= link_to "Sign Out", signout_path %>
  </p>
<% else %>
  <p><strong>Currently not signed in.</strong></p>
  <p>
    <%= link_to "Sign in through To Do List", "/auth/todo" %>
  </p>
<% end %>

app/views/variants/index.html.erb
<h1>Variants List</h1>

<ul id="tasks">
<% @products.each do |product| %>
  <li><%= link_to variant["name"], variant_path(variant['id']) %></li>
<% end %>
</ul>

<p id="logged_in">
  Logged in as <strong><%= current_user.name %></strong>.
  <%= link_to "Sign Out", signout_path %>
</p>

app/views/variants/show.html.erb
<ul>
  <%= @variant["name"] %>
  <%= link_to "Barcodes", barcode_path(@variant["upc"]) if @variant["upc"].present? %>
</ul>
<p><%= link_to "Back", root_path %></p>